version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
